### PR TITLE
Several fixes and refactors

### LINKED ISSUE #32: [Log] Silence logging by default
Currently, obs-websocket-js is quite noisy in the console with its log messages. It's generally standard for libraries to be "silent" -- that is: to only print output to the console if the consumer of that library has explicitly requested this behavior via some type of debug flag, configuration parameter, or environment variable.

@haganbmj If it's okay with you, I'll open a PR that silences all log statements by default unless some debug flag has been set to true.

### PR DESCRIPTION
**Pull request by Lange**
This gets rid of the `logLevel` dependency in favor of the [`debug`](https://github.com/visionmedia/debug) module. `debug` has a few advantages:

- Because `npm` does some degree of flattening, it's possible that multiple modules (or even the application which consumes `obs-websocket-js`) might end up with the same reference to a `logLevel` instance. This makes it impossible to silence `obs-websocket-js`'s log output without potentially interefering with the log output of other modules or applications running in the same Node.js context.
- `debug` provides a consistent, standardized method of configuration via environment variables.

Closes #32.

### CODE REVIEW

File: lib/Socket.js [hunk 1]
```diff
@@ -40,16 +40,16 @@ class Socket extends EventEmitter {
...
       originalEmit.apply(this, arguments);
     };
 
     this.connect({address})
       .then(() => {
         this.authenticate({password});
-      })
-      .catch(err => {
-        log.error('Connection or Authentication failed.', err);
+      }, err => {
```
Comment (haganbmj) [inline lib/Socket.js]: ahh, so that's the proper way to do that. Awesome.

Comment (Lange) [inline lib/Socket.js]: Oh actually, let me test that real quick before you merge. I'm not 100% sure that will work as I think.

Comment (haganbmj) [inline lib/Socket.js]: Tried #connect() without a catch and got a console warning about an uncaught promise.

File: lib/OBSWebSocket.js [hunk 2]
```diff
@@ -37,20 +35,20 @@ class OBSWebSocket extends Socket {
       const messageId = args['message-id'] = generateMessageId(); // eslint-disable-line no-multi-assign
 
       // Submit the request to the websocket.
-      log.debug('[Core:send]', messageId, requestType, args);
+      debug('[send] %s %s %O', messageId, requestType, args);
       this._socket.send(JSON.stringify(args));
```
Comment (haganbmj) [inline lib/OBSWebSocket.js]: Also just noticed that you don't get proper promise rejection when sending a request while not connected to a websocket.

Comment (Lange) [inline lib/OBSWebSocket.js]: Yeah, working on debugging some unhandled rejections right now.

Comment (Lange) [inline lib/OBSWebSocket.js]: Ah okay, it's because of the automatic call to `this.connect` that happens in the constructor for the `Socket` class. I don't think there's a good way for us to return this promise.

It might be best to get rid of this automatic `connect` and instead mandate that the consumer calls `.connect` themselves. What are your thoughts on that?

Comment (haganbmj) [inline lib/OBSWebSocket.js]: Yeah, I had it that way originally. You had to construct the object, call connect, then check getAuthRequired, then call authenticate. Not at all opposed to going back to that or something similar. Might be able to hide the getAuthRequired call in one of those.

Comment (haganbmj) [inline lib/OBSWebSocket.js]: What I had meant though is that if there's no socket connection sending any request produces an error here, which apparently isn't used as a reject. That's a separate issue from wrapping the `.connect()` function.

```
obs.getCurrentScene().then(data => { console.log('success'); }).catch(err => { console.log(err); });
> WebSocket is already in CLOSING or CLOSED state.
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
```

Comment (Lange) [inline lib/OBSWebSocket.js]: Ahh okay, I will look into that as well.

I've found and fixed a few other issues. This PR is going to be a little messy and deal with a few different concerns at once, unfortunately.

Comment (haganbmj) [inline lib/OBSWebSocket.js]: Can't be any worse than this project's commit history.
I can just open a separate issue for uncaught rejects in `send`. Doesn't necessarily have to go with this. I can certainly give it a shot after work.

Comment (Lange) [inline lib/OBSWebSocket.js]: I've already got it sorted! It's just a few lines so I'll hide my crimes in this pull request. :eyes:

Comment (haganbmj) [inline lib/OBSWebSocket.js]: Opened an issue for later.
https://github.com/haganbmj/obs-websocket-js/issues/34

Pretty sure it's as easy as just rejecting early if there's no socket connection.
The plugin itself will return a reject if you're not authenticated, so that should be sufficient.

Comment (haganbmj) [inline lib/OBSWebSocket.js]: Sounds like you beat me to it.

**Comment by Lange** [comment]
Alright, I broke things up as best I could into separate commits. My suggestion is to do a rebase merge to preserve the commit log here.

There's still more to do, but it can be done outside of this already-crowded PR.

**Comment by Lange** [comment]
Once this is merged, the next thing to tackle is tests (which will of course mean fixing all the bugs that crop up in the process).

**Comment by haganbmj** [comment]
Agreed on a rebase merge.

File: lib/Socket.js [hunk 3]
```diff
@@ -59,71 +51,104 @@ class Socket extends EventEmitter {
...
         } else {
           this.emit('obs:internal:event', data);
         }
-      };
-    });
+      });
+
+      await this._authenticate(args.password);
+
+      this._socket.once('close', () => {
```
Comment (haganbmj) [inline lib/Socket.js]: Note to self: Verify that this works in browser. Not entirely sure all WebSocket implementations support `.once`

Comment (Lange) [inline lib/Socket.js]: Ahh yeah good call -- I haven't even been thinking about browser. We'll need to write browser tests as well at some point.

Comment (haganbmj) [inline lib/Socket.js]: Yeah, just a thought I had since I'm not packing `ws` into the distributable.
Not completely opposed to requiring people run with some enhanced Socket implementation though. Standardizes it across multiple browsers.
